import { ROUTER_PATH } from "./RouterPath";

export const ALLOWED_PATH = [
    ROUTER_PATH.HOME.ROOT,
    ROUTER_PATH.FAVORITE.ROOT,
    ROUTER_PATH.SIGNUP,
    ROUTER_PATH.UPDATE_USER_INFO,
    ROUTER_PATH.UPDATE_USER_PASSWORD,
];